import { Box, Container, Divider, Stack, Typography } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import PrimaryButton from "../components/buttons/primaryButton";
import EventCard from "../components/events/event-card";
import Header from "../components/header";
import Login from "../components/page-ui-components/authentication/login";
const Home = () => {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Artery Low Fidelity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login />
    </div>
  );
};

export default Home;
